# Generated by Django 5.0.4 on 2024-05-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends_only', 'Friends Only')], default='public', max_length=32),
        ),
    ]
