# Generated by Django 5.0.4 on 2024-05-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_friendship_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
