name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            docker pull registry.gabrielkaszewski.dev/thoughts:latest
            docker pull registry.gabrielkaszewski.dev/thoughts-frontend:latest
            docker compose -f /opt/thoughts/docker-compose.yml up -d
