name: Build and Deploy Thoughts

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy-local:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Docker Versions
        run: |
          docker --version
          docker compose version

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env

      - name: Rebuild and Deploy with Docker Compose
        run: |
          docker compose -f compose.prod.yml pull
          docker compose -f compose.prod.yml up -d --build

          # Clean up any old, unused images to save disk space
          docker image prune -f