[package]
name = "activitypub-base"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio        = { workspace = true }
futures      = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
uuid         = { workspace = true }
chrono       = { workspace = true }
anyhow       = { workspace = true }
tracing      = { workspace = true }
async-trait  = { workspace = true }
axum         = { workspace = true }
reqwest      = { workspace = true }
url          = { workspace = true }
domain       = { workspace = true }

activitypub_federation = "0.7.0-beta.11"
enum_delegate          = "0.2"
