[package]
name = "activitypub"
version = "0.1.0"
edition = "2021"

[dependencies]
activitypub-base       = { workspace = true }
domain                 = { workspace = true }
url                    = { workspace = true }
serde                  = { workspace = true }
serde_json             = { workspace = true }
anyhow                 = { workspace = true }
chrono                 = { workspace = true }
uuid                   = { workspace = true }
async-trait            = { workspace = true }
tracing                = { workspace = true }
