[package]
name = "bootstrap"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "thoughts"
path = "src/main.rs"

[dependencies]
presentation        = { workspace = true }
domain              = { workspace = true }
postgres            = { workspace = true }
postgres-search     = { workspace = true }
postgres-federation = { workspace = true }
activitypub         = { workspace = true }
k-ap = { git = "https://git.gabrielkaszewski.dev/GKaszewski/k-ap.git", tag = "v0.1.0" }
nats                = { workspace = true }
event-transport     = { workspace = true }
auth                = { workspace = true }
sqlx                = { workspace = true }
async-nats          = { workspace = true }
async-trait         = { workspace = true }
tokio               = { workspace = true, features = ["full"] }
axum                = { workspace = true }
tower-http          = { workspace = true }
tracing             = { workspace = true }
tracing-subscriber  = { workspace = true }
dotenvy             = { workspace = true }
tower_governor      = "0.8"
http                = "1"
